services:
  - type: web
    name: handwritten-digits-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn handwritten_digits_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: handwritten_digits_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.9.16"
      - key: DISABLE_COLLECTSTATIC
        value: "1"  # Add this if you're not using static files
    plan: free
    numInstances: 1

databases:
  - name: handwritten_digits_db
    plan: free
    databaseName: handwritten_digits
    user: handwritten_user